apiVersion: v1
kind: Service
metadata:
  name: vpro-app-service
spec:
  selector:
    app: vproapp
  type: ClusterIP
  ports:
  - port: 8080
    protocol: TCP
    targetPort: vproapp-port
    type: ClusterIP